version: '3.1'

services:
    db:
        image: tumeplay-pgsql
        restart: always
        environment:
            POSTGRES_USER: database_user
            POSTGRES_PASSWORD: database_password
            POSTGRES_DB: database_name
        ports:
            - 5432:5432

    backend:
        image: tumeplay-backend
        restart: always
        depends_on:
          - "db"
        environment:
            JWT_SECRET: token_secret
            DATABASE_HOST: db
            DATABASE_NAME: database_name
            DATABASE_LOGIN: database_user
            DATABASE_PASSWORD: database_password
            DATABASE_FORCE: 0
            SERVER_PORT: 5000
            DEFAULT_ADMIN_LOGIN: default@admin.com
            DEFAULT_ADMIN_PASSWORD: default_password
            MONDIALRELAY_ID: relay_id
            MONDIALRELAY_SECRET: relay_secret
        ports:
            - 5000:5000
